// AUTH Actions
export const SET_APP_AUTH_STATE = 'SET_APP_AUTH_STATE';

export const SET_DEVICE_TOKEN = 'SET_DEVICE_TOKEN';

export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const FORGOT_PASSWORD_PENDING = 'FORGOT_PASSWORD_PENDING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const SEARCH_FAQS_PENDING = 'SEARCH_FAQS_PENDING';
export const SEARCH_FAQS_SUCCESS = 'SEARCH_FAQS_SUCCESS';
export const SEARCH_FAQS_ERROR = 'SEARCH_FAQS_ERROR';

export const UPDATE_SETTINGS_PENDING = 'UPDATE_SETTINGS_PENDING';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';
export const UPDATE_SETTINGS_ERROR = 'UPDATE_SETTINGS_ERROR';

export const SUBMIT_SUPPORT_MSG_PENDING = 'SUBMIT_SUPPORT_MSG_PENDING';
export const SUBMIT_SUPPORT_MSG_SUCCESS = 'SUBMIT_SUPPORT_MSG_SUCCESS';
export const SUBMIT_SUPPORT_MSG_ERROR = 'SUBMIT_SUPPORT_MSG_ERROR';

export const SUBMIT_REFERRAL_CODE_PENDING = 'SUBMIT_REFERRAL_CODE_PENDING';
export const SUBMIT_REFERRAL_CODE_SUCCESS = 'SUBMIT_REFERRAL_CODE_SUCCESS';
export const SUBMIT_REFERRAL_CODE_ERROR = 'SUBMIT_REFERRAL_CODE_ERROR';

export const LOGOUT = 'LOGOUT';

// PRODUCT Actions

export const SEARCH_DEALS_PENDING = 'SEARCH_DEALS_PENDING';
export const SEARCH_DEALS_SUCCESS = 'SEARCH_DEALS_SUCCESS';
export const SEARCH_DEALS_ERROR = 'SEARCH_DEALS_ERROR';

export const SEARCH_DEALS_VIA_CATEGORY_PENDING =
  'SEARCH_DEALS_VIA_CATEGORY_PENDING';
export const SEARCH_DEALS_VIA_CATEGORY_SUCCESS =
  'SEARCH_DEALS_VIA_CATEGORY_SUCCESS';
export const SEARCH_DEALS_VIA_CATEGORY_ERROR =
  'SEARCH_DEALS_VIA_CATEGORY_ERROR';

export const SEARCH_PRODUCTS_PENDING = 'SEARCH_PRODUCTS_PENDING';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR';

export const CLEAR_SEARCH_PRODUCTS = 'CLEAR_SEARCH_PRODUCTS';

export const GET_CATEGORIES_INFO_IDLE = 'GET_CATEGORIES_INFO_IDLE';
export const GET_CATEGORIES_INFO_PENDING = 'GET_CATEGORIES_INFO_PENDING';
export const GET_CATEGORIES_INFO_SUCCESS = 'GET_CATEGORIES_INFO_SUCCESS';
export const GET_CATEGORIES_INFO_ERROR = 'GET_CATEGORIES_INFO_ERROR';
export const CLEAR_GET_CATEGORIES_INFO = 'CLEAR_GET_CATEGORIES_INFO';

export const GET_CATEGORIES_INFO_WITH_TOKEN_IDLE =
  'GET_CATEGORIES_INFO_WITH_TOKEN_IDLE';
export const GET_CATEGORIES_INFO_WITH_TOKEN_PENDING =
  'GET_CATEGORIES_INFO_WITH_TOKEN_PENDING';
export const GET_CATEGORIES_INFO_WITH_TOKEN_SUCCESS =
  'GET_CATEGORIES_INFO_WITH_TOKEN_SUCCESS';
export const GET_CATEGORIES_INFO_WITH_TOKEN_ERROR =
  'GET_CATEGORIES_INFO_WITH_TOKEN_ERROR';
export const CLEAR_GET_CATEGORIES_INFO_WITH_TOKEN =
  'CLEAR_GET_CATEGORIES_INFO_WITH_TOKEN';

export const SAVE_PRODUCT_PENDING = 'SAVE_PRODUCT_PENDING';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_ERROR = 'SAVE_PRODUCT_ERROR';

export const REMOVE_PRODUCT_PENDING = 'REMOVE_PRODUCT_PENDING';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_ERROR = 'REMOVE_PRODUCT_ERROR';

export const MY_SAVED_PRODUCTS_PENDING = 'MY_SAVED_PRODUCTS_PENDING';
export const MY_SAVED_PRODUCTS_SUCCESS = 'MY_SAVED_PRODUCTS_SUCCESS';
export const MY_SAVED_PRODUCTS_ERROR = 'MY_SAVED_PRODUCTS_ERROR';

export const SET_REFERRAL_CODE = 'SET_REFERRAL_CODE';

// CART Actions

export const SAVE_CART_INFO_PENDING = 'SAVE_CART_INFO_PENDING';
export const SAVE_CART_INFO_SUCCESS = 'SAVE_CART_INFO_SUCCESS';
export const SAVE_CART_INFO_ERROR = 'SAVE_CART_INFO_ERROR';

export const UPDATE_CART_INFO_PENDING = 'UPDATE_CART_INFO_PENDING';
export const UPDATE_CART_INFO_SUCCESS = 'UPDATE_CART_INFO_SUCCESS';
export const CLEAR_CART_INFO = 'CLEAR_CART_INFO';

export const CREATE_ORDER_PENDING = 'CREATE_ORDER_PENDING';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

export const CONFIRM_ORDER_PENDING = 'CONFIRM_ORDER_PENDING';
export const CONFIRM_ORDER_SUCCESS = 'CONFIRM_ORDER_SUCCESS';
export const CONFIRM_ORDER_ERROR = 'CONFIRM_ORDER_ERROR';

export const MY_ORDERS_PENDING = 'MY_ORDERS_PENDING';
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS';
export const MY_ORDERS_ERROR = 'MY_ORDERS_ERROR';

export const REDEEEM_ORDERS_PENDING = 'REDEEEM_ORDERS_PENDING';
export const REDEEEM_ORDERS_SUCCESS = 'REDEEEM_ORDERS_SUCCESS';
export const REDEEEM_ORDERS_ERROR = 'REDEEEM_ORDERS_ERROR';
